export const productSelectors = {
  allProductsTitle: '.features_items h2.title',
  productCards: '.features_items .product-image-wrapper',
  productInfo: '.productinfo',
  searchButton: '#submit_search',
  productName: '.productinfo p',
  productPrice: '.productinfo h2',
  continueShoppingButton: '#cartModal button[data-dismiss="modal"]',
  searchInput: '#search_product',
 addedModalTitle: '#cartModal .modal-title',
  searchedProductsTitle: '.features_items h2.title',
  viewProductLinkById: (id: number): string => `a[href="/product_details/${id}"]`,
  addProductById: (id: number): string => `a[data-product-id="${id}"]`,
  addedModal: '#cartModal',
  detailAddToCartButton: 'button.cart',
  viewCartModalLink: '#cartModal a[href="/view_cart"]',
  productDetails: '.product-information',
  detailQuantityInput: '#quantity',
  
} as const
